# Generated by OpenCode on 2026-01-28
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name_ru", models.CharField(max_length=200)),
                ("name_kk", models.CharField(max_length=200)),
                ("name_en", models.CharField(max_length=200)),
                ("location_ru", models.CharField(max_length=200)),
                ("location_kk", models.CharField(max_length=200)),
                ("location_en", models.CharField(max_length=200)),
                ("description_ru", models.TextField()),
                ("description_kk", models.TextField()),
                ("description_en", models.TextField()),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="FeedbackMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
            ],
            options={"ordering": ["-created_at"], "abstract": False},
        ),
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_ru", models.CharField(max_length=220)),
                ("title_kk", models.CharField(max_length=220)),
                ("title_en", models.CharField(max_length=220)),
                ("link_url", models.URLField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["order", "title_ru"], "abstract": False},
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_ru", models.CharField(max_length=220)),
                ("title_kk", models.CharField(max_length=220)),
                ("title_en", models.CharField(max_length=220)),
                ("summary_ru", models.TextField()),
                ("summary_kk", models.TextField()),
                ("summary_en", models.TextField()),
                ("published_at", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["-published_at"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_ru", models.CharField(max_length=200)),
                ("title_kk", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("description_ru", models.TextField()),
                ("description_kk", models.TextField()),
                ("description_en", models.TextField()),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_ru", models.CharField(max_length=200)),
                ("title_kk", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("description_ru", models.TextField()),
                ("description_kk", models.TextField()),
                ("description_en", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["order", "title_ru"], "abstract": False},
        ),
        migrations.CreateModel(
            name="StructureUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_ru", models.CharField(max_length=200)),
                ("title_kk", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("description_ru", models.TextField()),
                ("description_kk", models.TextField()),
                ("description_en", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["order", "title_ru"], "abstract": False},
        ),
        migrations.CreateModel(
            name="TrainingProgram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_ru", models.CharField(max_length=200)),
                ("title_kk", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("description_ru", models.TextField()),
                ("description_kk", models.TextField()),
                ("description_en", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["order", "title_ru"], "abstract": False},
        ),
    ]
