# Generated by OpenCode on 2026-01-28
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="focus_ru",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="branch",
            name="focus_kk",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="branch",
            name="focus_en",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label_ru", models.CharField(max_length=200)),
                ("label_kk", models.CharField(max_length=200)),
                ("label_en", models.CharField(max_length=200)),
                ("value", models.CharField(max_length=50)),
                ("suffix", models.CharField(blank=True, max_length=20)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["order", "label_ru"], "abstract": False},
        ),
        migrations.CreateModel(
            name="DocumentCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_ru", models.CharField(max_length=200)),
                ("title_kk", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["order", "title_ru"], "abstract": False},
        ),
        migrations.CreateModel(
            name="DocumentEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_ru", models.CharField(max_length=220)),
                ("title_kk", models.CharField(max_length=220)),
                ("title_en", models.CharField(max_length=220)),
                ("link_url", models.URLField()),
                ("published_at", models.DateField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="main.documentcategory",
                    ),
                ),
            ],
            options={"ordering": ["-published_at", "title_ru"], "abstract": False},
        ),
        migrations.CreateModel(
            name="AccreditationItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_ru", models.CharField(max_length=220)),
                ("title_kk", models.CharField(max_length=220)),
                ("title_en", models.CharField(max_length=220)),
                ("description_ru", models.TextField()),
                ("description_kk", models.TextField()),
                ("description_en", models.TextField()),
                ("issued_at", models.DateField()),
            ],
            options={"ordering": ["-issued_at"], "abstract": False},
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_ru", models.CharField(max_length=200)),
                ("title_kk", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200)),
                ("location_ru", models.CharField(max_length=200)),
                ("location_kk", models.CharField(max_length=200)),
                ("location_en", models.CharField(max_length=200)),
                ("description_ru", models.TextField()),
                ("description_kk", models.TextField()),
                ("description_en", models.TextField()),
                ("deadline", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["-created_at"], "abstract": False},
        ),
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question_ru", models.CharField(max_length=240)),
                ("question_kk", models.CharField(max_length=240)),
                ("question_en", models.CharField(max_length=240)),
                ("answer_ru", models.TextField()),
                ("answer_kk", models.TextField()),
                ("answer_en", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["order", "question_ru"], "abstract": False},
        ),
    ]
